apiVersion: v1
kind: Service
metadata:
  name: webserver-1
spec:
  selector:
    app: webserver-1
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-1
  labels:
    app: webserver-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-1
  template:
    metadata:
      labels:
        app: webserver-1
    spec:
      containers:
      - name: webserver-1
        image: registry.redhat.io/rhel8/nginx-120:1-44
        ports:
        - containerPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webserver-1
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: webserver-1
